### ISSUE TITLE
Need input for section 6

### ISSUE THREAD

**Issue by richard-olav** [actris/data-management-plan#20]
Need a few lines on where data is stored. Storage of data, where all of the data is physically stored, will be seperate sub-section for each DC unit.

**Comment by richard-olav** [comment]
Currently, the content in section 6, is taken from the old DMP, please update!

**Comment by tukiains** [comment]
CLU updated section 6.3.

**Comment by LuciaMona** [comment]
done

**Comment by richard-olav** [comment]
ACCESS and In Situ also done
