### ISSUE TITLE
GARRlic

### ISSUE THREAD

**Issue by LuciaMona** [actris/data-management-plan#32]
I found into ACCESS the GARRLIC product from the NFs which cannot be . We have a dataflow for the ARES considering lidar and photomter togother which are mandatory for the NFs of aerosol remote sensing, so that those products are ARES products. @CNRS please revise accordingly. I just moved a line from the table of the products, but you shoudl check this aspect carefully everywhere.

**Comment by richard-olav** [comment]
Maybe @nicolas-pascal can have a look at this?

**Comment by richard-olav** [comment]
This should now how been fixed by Nicolas (https://github.com/actris/data-management-plan/commit/6ee409332b1a0f196732e848f66327c1375a2cb2#diff-9799927089e1630b36d3a2e45f98a94a).
